-- ============================================================
-- V001 : Create Tables
-- Schema  : MEDUIT_DEX.SFTP_INGESTION
-- Date    : 2026-07-01
-- ============================================================

CREATE DATABASE IF NOT EXISTS MEDUIT_DEX;
CREATE SCHEMA   IF NOT EXISTS MEDUIT_DEX.SFTP_INGESTION;

USE DATABASE MEDUIT_DEX;
USE SCHEMA   SFTP_INGESTION;


CREATE OR REPLACE TABLE FILE_BATCH_HEADER
(
    HEADER_ID     NUMBER IDENTITY(1,1),
    CLIENT_CODE   VARCHAR(50)  NOT NULL,
    CLIENT_NAME   VARCHAR(200) NOT NULL,
    SOURCE_SYSTEM VARCHAR(100),
    ROOT_FOLDER   VARCHAR(500),
    ACTIVE_FLAG   CHAR(1)      DEFAULT 'Y',
    CREATED_BY    VARCHAR(100),
    CREATED_DATE  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY    VARCHAR(100),
    UPDATED_DATE  TIMESTAMP,
    CONSTRAINT PK_FILE_BATCH_HEADER PRIMARY KEY (HEADER_ID)
);


CREATE OR REPLACE TABLE FILE_BATCH_FOLDER
(
    FOLDER_ID     NUMBER IDENTITY(1,1),
    HEADER_ID     NUMBER       NOT NULL,
    YEAR_MONTH    VARCHAR(7),
    FOLDER_NAME   VARCHAR(100),
    FOLDER_PATH   VARCHAR(1000),
    FOLDER_STATUS VARCHAR(30)  DEFAULT 'NEW',
    SCANNED_DATE  TIMESTAMP,
    ACTIVE_FLAG   CHAR(1)      DEFAULT 'Y',
    CREATED_BY    VARCHAR(100),
    CREATED_DATE  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP(),
    APPROVED_BY   VARCHAR(100),
    APPROVED_DATE TIMESTAMP,
    CONSTRAINT PK_FILE_BATCH_FOLDER PRIMARY KEY (FOLDER_ID)
);


CREATE OR REPLACE TABLE FILE_BATCH_DETAIL
(
    DETAIL_ID        NUMBER IDENTITY(1,1),
    FOLDER_ID        NUMBER       NOT NULL,
    FILE_NAME        VARCHAR(500) NOT NULL,
    FILE_TYPE        VARCHAR(100),
    FILE_EXTENSION   VARCHAR(20),
    FILE_PATH        VARCHAR(2000),
    FILE_SIZE_BYTES  NUMBER,
    FILE_HASH        VARCHAR(64),
    FILE_STATUS      VARCHAR(30)  DEFAULT 'DISCOVERED',
    -- DISCOVERED → APPROVED / REJECTED → INGESTED / FAILED
    APPROVED_BY      VARCHAR(100),
    APPROVED_DATE    TIMESTAMP,
    REJECTED_BY      VARCHAR(100),
    REJECTED_DATE    TIMESTAMP,
    REJECTION_REASON VARCHAR(1000),
    INGESTED_BY      VARCHAR(100),
    INGESTED_DATE    TIMESTAMP,
    ROWS_LOADED      NUMBER,
    CREATED_BY       VARCHAR(100),
    CREATED_DATE     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY       VARCHAR(100),
    UPDATED_DATE     TIMESTAMP,
    CONSTRAINT PK_FILE_BATCH_DETAIL PRIMARY KEY (DETAIL_ID)
);


CREATE OR REPLACE TABLE FILE_ACTIVITY_LOG
(
    ACTIVITY_ID      NUMBER IDENTITY(1,1),
    HEADER_ID        NUMBER,
    FOLDER_ID        NUMBER,
    DETAIL_ID        NUMBER,
    ACTIVITY_TYPE    VARCHAR(50),
    ACTIVITY_STATUS  VARCHAR(30),
    ACTIVITY_MESSAGE VARCHAR(4000),
    EXECUTED_BY      VARCHAR(100),
    EXECUTED_TIME    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP(),
    DURATION_SECONDS NUMBER,
    ERROR_CODE       VARCHAR(100),
    ERROR_MESSAGE    VARCHAR(4000)
);